name: Stirling PDF
version: "2.14.2"
slug: stirling-pdf
description: Locally hosted web application for various PDF operations
url: https://github.com/Stirling-Tools/Stirling-PDF
arch:
  - amd64
  - aarch64
startup: services
boot: auto
panel_icon: mdi:file-pdf-box
ports:
  8080/tcp: 2080
ports_description:
  8080/tcp: Web interface
webui: http://[HOST]:[PORT:8080]
